name: test-on-pr
on: 
  push:
    branches:
      - main
  pull_request
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Actions
        uses: actions/checkout@v3


      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Setup Cargo
        uses: actions-rs/cargo@v1
        with:
          command: test