name: test-on-pr
on: 
  push:
    branches:
      - main
    paths:
      - '/apps/backend/**'
  pull_request:
    paths:
      - '/apps/backend/**'
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Actions
        uses: actions/checkout@v3


      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test --manifest-path ./apps/backend/Cargo.toml
